### ISSUE TITLE
Usability issue - All projects referencing PDMFramework need to be signed

### ISSUE THREAD

**Issue by AmenJlili** [BlueByteSystemsInc/PDMFramework#10]
Because we are signing PDMFramework, I have found in some instances that the addin main project and all of its project references need to be signed as well. This presents a usability issue that need addressing.

**Comment by Alex-Egorchatov** [comment]
Are you sure there is an issue?

I have checked the CurnellPumps add-in. Both main and testing projects reference the PDMFramework. The testing project also references the main one, yet only the main project has to be signed to work.
A similar story is with the BoshTransition add-in. The main project is signed, the testing one is not.

**Comment by AmenJlili** [comment]
Yup. You're right. I should have said the addin project and any projects the addin references (other projects).
