### ISSUE TITLE
SetStatus2 is resetting the progress bar and the elapsed time in the tasklist the administration tool

### ISSUE THREAD

**Issue by AmenJlili** [BlueByteSystemsInc/PDMFramework#14]
**Issue:**

SetStatus2 uses IEdmTaskInstance::SetStatus. Tasks that use PDMFramework do not have proper elapsed time or progress in the administration tool. After reading [this](http://help.solidworks.com/2019/English/api/epdmapi/Schedule_Task_to_Find_Files_in_State_Addin_Example_CSharp.htm), I noticed that SetStatus is only used to set to change the [task status](http://help.solidworks.com/2017/english/api/epdmapi/epdm.interop.epdm~epdm.interop.epdm.edmtaskstatus.html). Any other progress is done through SetProgress.

**Solution:**

Implement SetProgress to report progress to the user unless when explicitly needing to fail, suspend, resume cancel or complete the task in which case use SetStatus with no message whatsoever.

**Comment by AmenJlili** [comment]
We need to test what happens when : 
- task gets cancelled. 
- task gets suspended and resumed.
- task fails.

**Comment by Alex-Egorchatov** [comment]
Very important note: the CancellationException class must be public, not internal.

**Comment by AmenJlili** [comment]
100 per cent. Good catch !

**Comment by Alex-Egorchatov** [comment]
So, the feature works fine. I have only one small concern: when the task is paused, the elapsed time continues to increment. If it is the expected behavior, I will merge branch 14 with Master and deploy the package under version 47.

**Comment by AmenJlili** [comment]
Please merge tomorrow and include the ticket # in the commit message....
