### ISSUE TITLE
Remove all unsigned dependencies

### ISSUE THREAD

**Issue by AmenJlili** [BlueByteSystemsInc/PDMFramework#17]
I think it might be wise to have as fewer dependencies as we can. 

Right we are using these: 
```

  <package id="BlueByte.SOLIDWORKS.PDMProfessional.Interops" version="2021.0.0" targetFramework="net472" />
  <package id="Microsoft.WindowsAPICodePack-Core" version="1.1.0.2" targetFramework="net472" />
  <package id="Microsoft.WindowsAPICodePack-Shell" version="1.1.0.0" targetFramework="net472" />
  <package id="Newtonsoft.Json" version="13.0.1" targetFramework="net472" />
  <package id="SimpleInjector" version="5.3.2" targetFramework="net472" />
  <package id="StrongNamer" version="0.2.5" targetFramework="net472" />
```

1. We're only using Windows API code pack for the common open dialog which I think we can do ourselves.
2. We can drop use of Newtonsoft.Json in favor of XML serializer from .NET
3. I don't know what we're going to do with SimpleInjector since I can't a signed version. Since it's under a MIT license, we can safely include it in the source code provided that we update the license terms.

**Comment by Alex-Egorchatov** [comment]
I actually agree with this idea. The only reason why we need the StrongNamer is because of the WindowsAPICodePack packages. For some reason, these ones are causing the signing error. If we remove them, we can remove the StrongNamer as well.

Not sure about Newtonsoft and SimpleInjector, but Windows API and StrongNamer should really be handled.

**Comment by AmenJlili** [comment]
Let's start with Newtonsoft first:

This code sample belows shows to serialize and deserialize using XML serialization:

```
internal static class Extensions
{
    public static T Deserialize<T>(this string value)
    {
        var xmlSerializer = new XmlSerializer(typeof(T));

        return (T)xmlSerializer.Deserialize(new StringReader(value));
    }

    public static string Serialize<T>(this T value)
    {
        if (value == null)
            return string.Empty;

        var xmlSerializer = new XmlSerializer(typeof(T));

        using (var stringWriter = new StringWriter())
        {
            using (var xmlWriter = XmlWriter.Create(stringWriter, new XmlWriterSettings { Indent = true }))
            {
                xmlSerializer.Serialize(xmlWriter, value);
                return stringWriter.ToString();
            }
        }
    }
}
```

@Alex-Egorchatov : I will take care of the Windows API stuff.

**Comment by AmenJlili** [comment]
I removed these packages:
```
  <package id="Microsoft.WindowsAPICodePack-Core" version="1.1.0.2" targetFramework="net472" />
  <package id="Microsoft.WindowsAPICodePack-Shell" version="1.1.0.0" targetFramework="net472" />
  <package id="StrongNamer" version="0.2.5" targetFramework="net472" />
```

Since Windows API code pack does not look to be signed.

SimpleInjector and Newtonsoft are both signed.

**Comment by AmenJlili** [comment]
No need to remove all dependencies. Just the unsigned now...
