### ISSUE TITLE
Strong name reference issue

### ISSUE THREAD

**Issue by Alex-Egorchatov** [BlueByteSystemsInc/PDMFramework#2]
The PDMAddInFramework is signed with StrongKey.pfx file. That means that all of its references must also be signed and have Strong Name property set to True. For some reason, it cannot be done manually for all NuGet packages.
To solve this issue, the NuGet package StrongNamer by Daniel Plaisted needs to be installed.

**Comment by AmenJlili** [comment]
This is causing us having to sign all project that use PDMFramework. We need to investigate a better way.

**Comment by AmenJlili** [comment]
After further investigation, we are going to to drop use of strong renamer. The rule goes as follow: 
**- Unsigned assemblies can reference signed assemblies.** 
**- Signed assemblies assemblies cannot reference unsigned assemblies.**

We have just have to respect that.
