### ISSUE TITLE
VSTemplate issue with files under task

### ISSUE THREAD

**Issue by AmenJlili** [BlueByteSystemsInc/PDMFramework#34]
TaskLaunch, Run, Setup, SetupButton.cs have a partial class called AddIn. The namespace in those files must match the one in AddIn.cs

We need to drop the ".task" from the namespace from those files. 

Does this make sense?

**Comment by avdynut** [comment]
@AmenJlili done, please test

**Comment by AmenJlili** [comment]
Will do. Thanks!

**Comment by AmenJlili** [comment]
Looks good. Thanks
