### ISSUE TITLE
Package the PDMFramework VS project template 

### ISSUE THREAD

**Issue by AmenJlili** [BlueByteSystemsInc/PDMFramework#7]
We need to use VSX SDX for this. We may need some outside help for this.

The goal of this is to publish our project templates on Visual Studio Extension marketplace.

**Comment by AmenJlili** [comment]
@avdynut 

Can you do me a favor and include the issue # in your future commit messages (so that the commit shows up in the history of the issue page).

Example: 
`git commit -m "#7 Added some changes"`

**Comment by avdynut** [comment]
@AmenJlili okay

**Comment by AmenJlili** [comment]
So basically there remain two tasks: 
- Make sure we use the latest version of the PDMAddInFramework. I'll take care of that myself. 
- Embed Interop Types = false for the references that start with EPDM. Can you check the comments in this question: https://stackoverflow.com/questions/69918538/pre-build-event-to-set-embed-interop-types-false-for-all-references-with-the-w

**Comment by avdynut** [comment]
@AmenJlili I already did as described in the comments, please check
